### ISSUE TITLE
Unexpected behavior observed

### ISSUE THREAD

**Issue by TheBarret** [wrefgtzweve/SpaceEngineersDLCUnlocker#10]
I do not have the full picture of what exactly is modified in these files, but I observed very weird behavior in the mods/dlc packages listing.
I've seen for instance that after I applied this patch i have duplicates and some mods become absent (but are downloaded and in the directory) and sometimes the DLC blocks themselves become locked again sporadically, ive tried putting the mods manually in the folder, only then I can use the mod that was previously missing.

Could this be the result of this patch I wonder?

**Comment by wrefgtzweve** [comment]
I haven't heard any other reports of this nor had these issues myself, however mods can conflict if they override default blocks. But  such a conflict would result in the block always being DLC locked.

**Comment by TheBarret** [comment]
> I haven't heard any other reports of this nor had these issues myself, however mods can conflict if they override default blocks. But such a conflict would result in the block always being DLC locked.

Alright, thanks for the reply! Seems more people have this issue, so its def not the patch, but Keen self (So we think).

Sorry to bother you ofc, I just had to make sure (isolate).

**Comment by wrefgtzweve** [comment]
Classic keen, in that case I'll close the issue. If you got any other issues feel free to let me know!
