### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Possiblespy** [wrefgtzweve/SpaceEngineersDLCUnlocker#11]
Hello wrefgtzweve, when i load up the game and look in my g menu dlc is still blocked, is there any common fixes?

**Comment by wrefgtzweve** [comment]
Are you using any mods? mods can override the default blocks and prevent this from working. Also make sure you installed it correctly.

**Comment by Possiblespy** [comment]
ill try without my mods thank you, as for instillation the content is located within the correct file. Ill give an update if removing my mods remedies the issue.

**Comment by Possiblespy** [comment]
all right i tried without mods and unfornatley nothing was fixed

**Comment by wrefgtzweve** [comment]
Must be a mis install then, try reinstalling it and make sure that it actually replaces files
