### ISSUE TITLE
no dlc heavy industry?

### ISSUE THREAD

**Issue by enricfur** [wrefgtzweve/SpaceEngineersDLCUnlocker#12]
![изображение](https://user-images.githubusercontent.com/103355441/176181055-beb2e7a5-f9b2-47cc-8ced-ad0d6ff02cf4.png)

**Comment by wrefgtzweve** [comment]
It's in there, are you using mods? Mods can override blocks which breaks this patch.

**Comment by enricfur** [comment]
this server without mods

**Comment by wrefgtzweve** [comment]
Try reinstalling it and make sure it's applied properly, the most recent update might've broken stuff for you.
