### ISSUE TITLE
Not working with latest updates

### ISSUE THREAD

**Issue by ToothlessBeaver** [wrefgtzweve/SpaceEngineersDLCUnlocker#14]
Any chance we can get an update on this? Thanks!

**Comment by wrefgtzweve** [comment]
Just tested, worked fine for me. Are you sure you installed it properly?

**Comment by ToothlessBeaver** [comment]
I just tried it on the automations Beta and its working now, i guess i already tried to edit the files on the public version thats why it didnt work.
