### ISSUE TITLE
Can't see the DLC tabs on the menu?

### ISSUE THREAD

**Issue by boltyboi** [wrefgtzweve/SpaceEngineersDLCUnlocker#16]
(don't mind the mods)
What I see:
![image](https://user-images.githubusercontent.com/58641698/231851120-02d3c561-a9e5-4d09-a021-f084e6f9dd28.png)
What I should see:
![image](https://user-images.githubusercontent.com/58641698/231851217-22491359-9c5d-48ac-bb53-5e118e26d968.png)

**Comment by wrefgtzweve** [comment]
I've just pushed an update that should've fixed it, i haven't tried it yet but I'm pretty sure it does. Let me know if the issue persists after getting the new version.

**Comment by boltyboi** [comment]
Perfect, they both show up now
![image](https://user-images.githubusercontent.com/58641698/231858975-5ebbe62b-cd99-49c0-9b56-2289a9e2acff.png)
Thanks again for updating this!

**Comment by wrefgtzweve** [comment]
No problem, thanks for reporting!
