### ISSUE TITLE
cant paste dlc in multiplayer

### ISSUE THREAD

**Issue by Scrannefrank** [wrefgtzweve/SpaceEngineersDLCUnlocker#18]
since updating to the new version whenever i paste dlc blocks on a server it removes all dlc items i tried single player and it works fine

**Comment by wrefgtzweve** [comment]
I've tried this and haven't been able to reproduce it, i can use DLC blocks fine in a multiplayer server. It might be because you're pasting them, i haven't specifically tried that and don't have easy access to a server to test it.
