### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by cheespernx** [wrefgtzweve/SpaceEngineersDLCUnlocker#2]
Can u update this to the new one? Now we have the heavy space industries and the warfare

**Comment by wrefgtzweve** [comment]
Both are in already in this:

https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/blob/master/SpaceEngineers/Content/Data/CubeBlocks/CubeBlocks_Warfare1.sbc

https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/blob/master/SpaceEngineers/Content/Data/CubeBlocks/CubeBlocks_IndustrialPack.sbc
