### ISSUE TITLE
Can't see or use Heavy Industry Conveyor Pipe Caps

### ISSUE THREAD

**Issue by boltyboi** [wrefgtzweve/SpaceEngineersDLCUnlocker#20]
![image](https://user-images.githubusercontent.com/58641698/232560963-146af6ac-d0b2-4955-a29c-9841d6aae788.png)

don't mind the mods by the way
What I see:
![image](https://user-images.githubusercontent.com/58641698/232561043-f03c523d-6827-4eb5-a828-53ab25bce414.png)

What I should see:
(will try get an image shortly) - you get the idea though I can't see, find, or use the new conveyor caps for heavy industry pipes

guessing since it's new blocks added to an old DLC pack that you need to re-add this block or something

**Comment by wrefgtzweve** [comment]
Should be fixed now, good catch!

**Comment by boltyboi** [comment]
![image](https://user-images.githubusercontent.com/58641698/232836416-5757f4cb-bf2a-4e5c-8a46-117840739b1a.png)
Works perfect, and is in the corresponding menus:
![image](https://user-images.githubusercontent.com/58641698/232836524-528dbec3-7b80-499c-85ff-af41d72be32a.png)
thanks again!
