### ISSUE TITLE
warfare 2 dlc tab not apearing 

### ISSUE THREAD

**Issue by Superdie02** [wrefgtzweve/SpaceEngineersDLCUnlocker#23]
the tab with the warfare 2 is not in the game is this just a issue with mods or the unlocker?

**Comment by wrefgtzweve** [comment]
They should be in there, see <https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/blob/7cdb22530cdcb8b1ed07ce3d7a35eb6425eb2f5a/SpaceEngineers/Content/Data/BlockCategories.sbc#L31> as example, try without mods if you can.
