### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by FLUFFY788** [wrefgtzweve/SpaceEngineersDLCUnlocker#28]
This does not seem to work for me. I go to my space engineers folder and replace the content folder with the one provided. And I am only able to access the DLC that I own and base game items.

Am I missing something or has this been patched somehow?

![image](https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/assets/88108763/00c95812-b8fd-424c-96e8-7015622beb06)

**Comment by wrefgtzweve** [comment]
I don't think it's fixed in the game as i didn't see an update recently, do you use any mods? I know that some mods override default blocks thus breaking their changed dlc flags.

**Comment by FLUFFY788** [comment]
No mods.

> I don't think it's fixed in the game as i didn't see an update recently, do you use any mods? I know that some mods override default blocks thus breaking their changed dlc flags.

**Comment by DisFanJen** [comment]
Came to say the same thing.  Tried yesterday but all items still shows as locked.

**Comment by wrefgtzweve** [comment]
I've just tested it, it works fine for me

Fresh install:
![image](https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/assets/69946827/b7eb7e23-428f-4485-b50a-e7c43cf55dba)


With this repo applied:
![image](https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/assets/69946827/f9e863ec-d282-4855-9c84-3b924e5fc517)
![image](https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/assets/69946827/258cea24-e54c-4f01-af47-80252aa63638)

**Comment by wrefgtzweve** [comment]
Game updated, this method has now been patched. There's a link to a newer method in the readme.
