### ISSUE TITLE
decorative blocks #3 DLC out , need new version

### ISSUE THREAD

**Issue by Superdie02** [wrefgtzweve/SpaceEngineersDLCUnlocker#29]
could you update this so that the dlc is unlocked?

**Comment by VelociRandom** [comment]
This method unfortunately no longer works, the game actually checks whether your Steam account owns the DLC now.
Lamer's version has a workaround until someone manages to come up with a better solution: https://github.com/Lamer87/Space_Engineers_DLC_unlocker/issues/36

**Comment by Lamer87** [comment]
[This is the main page](https://github.com/Lamer87/Space_Engineers_DLC_unlocker)

**Comment by wrefgtzweve** [comment]
https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/commit/91181891e65274b717fce360b60033ba51b1fe9c
