### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Incorretc** [wrefgtzweve/SpaceEngineersDLCUnlocker#31]

**Comment by wrefgtzweve** [comment]
See https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker#this-is-now-obsolete-as-new-checks-have-been-introduced-to-the-game-however-theres-a-new-method-you-can-use-this-tool-for-space-engineers-dlcs-and-other-games-dlcs-httpsgithubcompointfeevcreaminstaller
