### ISSUE TITLE
Unlocking all skins :)

### ISSUE THREAD

**Issue by AidenCharming** [wrefgtzweve/SpaceEngineersDLCUnlocker#4]
Just wanted to let you know I found a workaround for wearing any skin as long as you have atleast one owned skin of each typ.e Check it out. https://imgur.com/a/MCTwsfd

**Comment by wrefgtzweve** [comment]
Won't this only be visible for yourself?

**Comment by AidenCharming** [comment]
Sadly yes, but it does work if you want to see yourself as certain skin.

**Comment by wrefgtzweve** [comment]
I'll mention it in the readme thanks for showing me!
