### ISSUE TITLE
Wasteland DLC missing

### ISSUE THREAD

**Issue by ghost** [wrefgtzweve/SpaceEngineersDLCUnlocker#5]
As shown here after installing the off-road Wheels are still locked
![image](https://user-images.githubusercontent.com/88629925/163528371-1142e5e7-450c-4f83-8b06-7d36b497250c.png)

**Comment by wrefgtzweve** [comment]
Should be accounted for, https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/blob/bc576b5e1a1bdc6a8710cda239c2bb7b66bcdf44/SpaceEngineers/Content/Data/CubeBlocks/CubeBlocks_ScrapRacePack.sbc#L296

I don't have any issues with it. Are you sure you installed it correctly? do the other dlcs work?

**Comment by ghost** [comment]
I'll try and install it again but I'm sure it was done correctly since I have the other things unlocked like the cockpit and the rest of the wasteland dlc

**Comment by wrefgtzweve** [comment]
Was it fixed after reinstalling?

**Comment by ghost** [comment]
Yes it did, something must have gone wrong on my end This time I downloaded the files from the repo not from the release zip maybe something is different there? Or maybe it was just a problem on my end, I'll check it out.

**Comment by ghost** [comment]
Something definitely went wrong on my end! Both are working as intended, my bad.
