### ISSUE TITLE
All DLC Blocks Locked When Adding Industrial Overhaul v1.6

### ISSUE THREAD

**Issue by NitroRiced** [wrefgtzweve/SpaceEngineersDLCUnlocker#6]
When adding the mod Industrial Overhaul, all the DLC's become locked once again, I'm not sure why. Do you think there's any way to fix this?

**Comment by wrefgtzweve** [comment]
Industrial Overhaul might overhaul/overwrite all the default blocks, I don't know if this is fixable on my end

**Comment by NitroRiced** [comment]
Were you unable to fix it? That's alright, I realised that only the blocks that need an industrial overhaul components to build are locked, so that does kind of make sense

**Comment by wrefgtzweve** [comment]
Yeah it likely overrides the default blocks or creates entirely new ones. I'll close this as this is not fixable by changing game files this way.

**Comment by NitroRiced** [comment]
ight thanks for your help.
